version: '3.9'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:7.4-fpm-alpine
    container_name: RpcApp
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  rabbitmq:
    hostname: "rabbitpoc"
    image: "rabbitmq:3-management"
    container_name: RpcRabbitMQ
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - 'rabbitmq_data:/data'
    networks:
        - app-network
    environment:
      RABBITMQ_DEFAULT_USER: siddhesh
      RABBITMQ_DEFAULT_PASS: demo1234
      RABBITMQ_DEFAULT_VHOST: "/"


#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  rabbitmq_data:
    driver: local
